apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: kitchen-monitor
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/mqtt
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "MQTTDevice"
  template:
    metadata:
      labels:
        device: kitchen-monitor
    spec:
      protocol:
        pattern: "AttributedTopic"
        client:
          server: "tcp://octopus-simulator-mqtt.octopus-simulator-system:1883"
        message:
          topic: "cattle.io/octopus/home/status/kitchen/:path"
      properties:
        - name: "doorState"
          path: "door/state"
          description: "The state of door"
          type: "string"
          annotations:
            type: "enum"
            format: "open,close"
        - name: "isLightOn"
          description: "The state of light"
          path: "light/switch"
          type: "boolean"
