# Adds namespace to all resources.
namespace: octopus-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: octopus-adaptor-agent-device-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: "octopus-adaptor-agent-device"
  app.kubernetes.io/version: "master"

## Images to overwrite the default images.
images:
  - name: rancher/octopus-adaptor-agent-device
    newName: rancher/octopus-adaptor-agent-device
    newTag: master

## NB(thxCode) Since kustomize v2.1.0, the `bases` field has been deprecated by `resources`, ref to:
## - https://github.com/kubernetes-sigs/kustomize/blob/v2.1.0/docs/v_2.1.0.md#field-changes--deprecations
## Select the appropriate kubectl to generate according to https://github.com/kubernetes-sigs/kustomize#kubectl-integration.
bases:
  - ../../crd
  - ../../rbac
  - ../../workload
